theme: jekyll-theme-chirpy

lang: en

title: Yann Fernandez Puig

tagline: Aspiring Software Engineer | EPITA 

description: >-
  3rd-year EPITA student specialized in low-level programming in C, seeking a technical internship for Autumn 2026.

url: "https://yannfp.github.io"

github:
  username: yannfp

social:
  name: Yann Fernandez Puig
  email: yann.ferpuig@gmail.com 
  links:
    - https://github.com/yannfp
    - https://www.linkedin.com/in/yann-fernandez-puig-a2a072312

category: /categories/:name/
